// A Словарные слова
const typeA = [
    { text: "ц..ганский", letter: "ы" },
    { text: 'б..тарея', letter: 'а' },
    { text: 'эксп..римент', letter: 'е' },
    { text: 'б..чёвка', letter: 'е' },
    { text: 'б..дон', letter: 'и' },
    { text: 'д..агональ', letter: 'и' },
    { text: 'велос..пед', letter: 'и' },
    { text: 'арт..ллерия', letter: 'и' },
    { text: 'вер..ница ', letter: 'е' },
    { text: 'фраз..ологический', letter: 'е' },
    { text: 'в..стибюль', letter: 'е' },
    { text: 'пал..садник', letter: 'и' },
    { text: 'м..раж ', letter: 'и' },
    { text: 'г..лерея', letter: 'а' },
    { text: 'ф..нтазия', letter: 'а' },
    { text: 'при..ритет', letter: 'о' },
    { text: 'гард..роб', letter: 'е' },
    { text: 'гастр..ном', letter: 'о' },
    { text: 'г..строном', letter: 'а' },
    { text: 'к..бинет ', letter: 'а' },
    { text: 'р..гулировать', letter: 'е' },
    { text: 'д..легат', letter: 'е' },
    { text: 'д..сциплина', letter: 'и' },
    { text: 'р..зультат', letter: 'е' },
    { text: 'в..негрет', letter: 'и' },
    { text: 'к..бинет', letter: 'а' },
    { text: 'д..летант', letter: 'и' },
    { text: 'м..кароны', letter: 'а' },
    { text: 'н..тюрморт ', letter: 'а' },
    { text: 'м..даль', letter: 'е' },
    { text: 'в..стибюль', letter: 'е' },
    { text: 'инж..нер', letter: 'е' },
    { text: 'интелл..генция', letter: 'и' },
    { text: 'в..негрет', letter: 'и' },
    { text: 'б..лкон', letter: 'а' },
    { text: 'к..блук ', letter: 'а' },
    { text: 'ф..нтан', letter: 'о' },
    { text: 'б..дминтон', letter: 'а' },
    { text: 'к..лач ', letter: 'а' },
    { text: 'ор..гинальный', letter: 'и' },
    { text: 'г..гиена', letter: 'и' },
    { text: 'ш..лун', letter: 'а' },
    { text: 'к..ндуктор', letter: 'о' },
    { text: 'к..вычки', letter: 'а' },
    { text: 'п..ртрет', letter: 'о' },
    { text: 'пр..цент', letter: 'о' },
    { text: 'к..рниз', letter: 'а' },
    { text: 'импр..визация', letter: 'о' },
    { text: 'б..лагур', letter: 'а' },
    { text: 'пост..раться (выполнить в срок)', letter: 'а' },
    { text: 'опп..нент', letter: 'о' },
    { text: 'в..трушка', letter: 'а' },
    { text: 'д..скуссия', letter: 'и' },
    { text: 'т..тальный', letter: 'о' },
    { text: 'р..гламент', letter: 'е' },
    { text: 'б..седа', letter: 'е' },
    { text: 'б..нзин', letter: 'е' },
    { text: 'ст..ллаж', letter: 'е' },
    { text: 'макул..тура', letter: 'а' },
    { text: 'б..стион', letter: 'а' },
    { text: 'д..легировать', letter: 'е' },
    { text: 'к..раси', letter: 'а' },
    { text: 'т..атральный', letter: 'е' },
    { text: 'ок..лдовать', letter: 'о' },
    { text: 'авиак..мпания', letter: 'о' },
    { text: 'г..потеза', letter: 'и' },
    { text: 'г..роизм', letter: 'е' },
    { text: 'к..мпонент', letter: 'о' },
    { text: 'альм..нах', letter: 'а' },
    { text: "р..квизит", letter: "е" },
    { text: "р..комендовать", letter: "е" },
    { text: "р..кошет", letter: "и" },
    { text: "р..естр", letter: "е" },
    { text: "р..жим", letter: "е" },
    { text: "р..жиссер", letter: "е" },
    { text: "с..нтиментальный", letter: "е" },
    { text: "с..нхронный", letter: "и" },
    { text: "сп..ртакиада", letter: "а" },
    { text: "рест..врация", letter: "а" },
    { text: "инт..ллектуальный", letter: "е" },
    { text: "предс..датель", letter: "е" },
    { text: "сб..режения", letter: "е" },
    { text: "обр..млять(гравюру)", letter: "а" },
    { text: "п..лемический", letter: "о" },
    { text: "разъ..снение", letter: "я" },
    { text: "см..калистый(ученик)", letter: "е" },
    { text: "д..лина", letter: "о" },
    { text: "м..хнатый", letter: "о" },
    { text: "подор..жание", letter: "о" },
    { text: "иск..жать(смысл)", letter: "а" },
    { text: "энц..клопедия", letter: "и" },
    { text: "ц..линдр", letter: "и" },
    { text: "р..форма", letter: "е" },
    { text: "анн..тация", letter: "о" },
    { text: "г..строном", letter: "а" },
    { text: "к..бинет", letter: "а" },
    { text: "р..гулировать", letter: "е" },
    { text: "д..легат", letter: "е" },
    { text: "д..сциплина", letter: "и" },
    { text: "выр..внять(поверхность)", letter: "о" },
    { text: "р..зультат", letter: "е" },
    { text: "в..негрет", letter: "и" },
    { text: "пон..мание", letter: "и" },
    { text: 'предл..жение', letter: 'о' },
    { text: 'зап..вать(водой)', letter: 'и' },
    { text: 'усм..ренный', letter: 'и' },
    { text: 'поч..тать(старших)', letter: 'и' },
    { text: 'б..ллетень', letter: 'ю' },
    { text: 'ош..ломленный', letter: 'е' },
    { text: 'разб..гатеть', letter: 'о' },
    { text: 'провозгл..шать', letter: 'а' },
    { text: 'к..рифей', letter: 'о' },
    { text: 'дел..катес', letter: 'и' },
    { text: 'панц..рь', letter: 'и' },
    { text: 'рац..ональный', letter: 'и' },
    { text: 'ц..вилизация', letter: 'и' },
    { text: 'просв..щение', letter: 'е' },
    { text: 'инт..ллект', letter: 'е' },
    { text: 'конт..нент', letter: 'и' },
    { text: 'сост..зание', letter: 'я' },
    { text: 'у..звить', letter: 'я' },
    { text: 'см..тение', letter: 'я' },
    { text: 'интелл..гентный', letter: 'и' },
    { text: 'брош..ра', letter: 'ю' },
    { text: 'параш..тный', letter: 'ю' },
    { text: 'параш..т', letter: 'ю' },
    { text: '(члены)ж..ри', letter: 'ю' },
    { text: 'насл..ждение', letter: 'а' },
    { text: 'рест..врация', letter: 'а' },
    { text: 'абаж..р', letter: 'у' },
    { text: 'об..ятельный', letter: 'а' },
    { text: 'симп..тичный', letter: 'а' },
    { text: 'ал..миний', letter: 'ю' },
    { text: 'б..ллетень', letter: 'ю' },
    { text: 'погл..щать', letter: 'о' },
    { text: 'вент..лятор', letter: 'и' },
    { text: 'верм..шель', letter: 'и' },
    { text: 'приподн..мать', letter: 'и' },
    { text: 'непром..каемый', letter: 'о' },
    { text: 'расч..т', letter: 'е' },
    { text: 'реш..тка', letter: 'е' },
    { text: 'об..зательно', letter: 'я' },
    { text: 'исп..лнение', letter: 'о' },
    { text: 'тр..нажер', letter: 'е' },
    { text: 'ч..стоплотный', letter: 'и' },
    { text: 'г..роизм', letter: 'е' },
    { text: 'к..ртон', letter: 'а' },
    { text: 'п..риод', letter: 'е' },
    { text: '(ударился)оз..мь', letter: 'е' },
    { text: 'оф..цер', letter: 'и' },
    { text: 'б..хрома', letter: 'а' },
    { text: 'экстр..мальный', letter: 'е' },
    { text: 'раст..рзать', letter: 'е' },
    { text: 'н..гилист', letter: 'и' },
    { text: 'приор..тет', letter: 'и' },
    { text: 'ф..нансист', letter: 'и' },
    { text: 'упр..жнение', letter: 'а' },
    { text: 'подв..ротня', letter: 'о' },
    { text: 'м..ридиан', letter: 'е' },
    { text: 'ап..льсин', letter: 'е' },
    { text: 'ош..ломленный', letter: 'е' },
    { text: 'прикр..ватный', letter: 'о' },
    { text: 'л..сток', letter: 'и' },
    { text: 'к..вать(головой)', letter: 'и' },
    { text: 'велос..пед', letter: 'и' },
    { text: 'галакт..ка', letter: 'и' },
    { text: 'к..мфорт', letter: 'о' },
    { text: 'п..лировать(мебель)', letter: 'о' },
    { text: 'н..циональный', letter: 'а' },
    { text: 'пок..ситься(от старости)', letter: 'о' },
    { text: 'в..кзал', letter: 'о' },
    { text: 'к..ллекционный', letter: 'о' },
    { text: 'потр..сающий', letter: 'я' },
    { text: 'ш..винизм', letter: 'о' },
    { text: 'ш..ковый', letter: 'ё' },
    { text: 'ш..мпол', letter: 'о' },
    { text: 'отр..сль', letter: 'а' },
    { text: 'укр..щавший(тигра)', letter: 'о' },
    { text: 'ярм..рка', letter: 'а' },
    { text: 'скр..пя(сердце)', letter: 'е' },
    { text: 'пос..деть(к старости)', letter: 'е' },
    { text: 'просв..щение', letter: 'е' },
    { text: 'п..ркет', letter: 'а' },
    { text: 'г..рняцкий', letter: 'о' },
    { text: 'погл..щение', letter: 'о' },
    { text: 'об..няние', letter: 'о' },
    { text: 'прид..ржать', letter: 'и' },
    { text: 'ид..ологический', letter: 'е' },
    { text: 'ч..столюбие', letter: 'е' },
    { text: 'зан..мательный', letter: 'и' },
    { text: 'отв..рить(дверь)', letter: 'о' },
    { text: 'подск..чить', letter: 'о' },
    { text: 'зак..снелый', letter: 'о' },
    { text: 'к..мендант', letter: 'о' },
    { text: 'см..нать(траву)', letter: 'и' },
    { text: 'укр..титель(тигров)', letter: 'о' },
    { text: 'симп..тичный', letter: 'а' },
    { text: 'посв..щение(другу)', letter: 'я' },
    { text: 'недос..гаемый', letter: 'и' },
    { text: 'у..звить', letter: 'я' },
    { text: 'с..дина(вволосах)', letter: 'е' },
    { text: 'стр..жайший', letter: 'о' },
    { text: 'подб..родок', letter: 'о' },
    { text: 'к..стюмер', letter: 'о' },
    { text: '(ударился)оз..мь', letter: 'е' },
    { text: 'см..ренный', letter: 'и' },
    { text: 'расч..ртить', letter: 'е' },
    { text: 'встр..чаемся', letter: 'е' },
    { text: '(крепкая)б..чёвка', letter: 'е' },
    { text: 'пропол..скать(бельё)', letter: 'о' },
    { text: 'г..ризонтальный', letter: 'о' },
    { text: 'разб..раться', letter: 'и' },
    { text: 'нач..нать', letter: 'и' },
    { text: 'п..рила', letter: 'е' },
    { text: 'распл..скать', letter: 'е' },
    { text: 'соч..тание', letter: 'е' },
    { text: 'возл..гать', letter: 'а' },
    { text: 'опров..ргать', letter: 'е' },
    { text: 'д..баты', letter: 'е' },
    { text: 'ист..нный', letter: 'и' },
    { text: 'б..рлога', letter: 'е' },
    { text: 'п..лотируемый', letter: 'и' },
    { text: 'глоб..листский', letter: 'а' },
    { text: 'к..раллы', letter: 'о' },
    { text: 'ос..бняк', letter: 'о' },
    { text: 'т..рговец', letter: 'о' },
    { text: 'об..грённый(кровью)', letter: 'а' },
    { text: 'м..заичный', letter: 'о' },
    { text: 'в..пиющий(случай)', letter: 'о' },
    { text: 'д..сантироваться', letter: 'е' },
    { text: '..нчоус', letter: 'а' },
    { text: '..укцион', letter: 'а' },
    { text: 'апп..тит', letter: 'е' },
    { text: 'р..гламент', letter: 'е' },
    { text: 'ав..нгард', letter: 'а' },
    { text: 'п..рила', letter: 'е' },
    { text: 'ар..стократ', letter: 'и' },
    { text: 'м..нистерство', letter: 'и' },
    { text: 'д..визион', letter: 'и' },
    { text: 'г..ризонт', letter: 'о' },
    { text: 'стр..тегия', letter: 'а' },
    { text: 'пр..оритет', letter: 'и' },
    { text: 'к..мфорт', letter: 'о' },
    { text: 'сп..раль', letter: 'и' },
    { text: 'б..рашек', letter: 'а' },
    { text: 'ф..рмат', letter: 'о' },
    { text: 'предв..рительный', letter: 'а' },
    { text: 'прид..рожный', letter: 'о' },
    { text: 'доск..нально', letter: 'о' },
    { text: 'б..лото', letter: 'о' },
    { text: 'нест..бильно', letter: 'а' },
    { text: 'ш..девр', letter: 'е' },
    { text: 'д..визия', letter: 'и' },
    { text: 'с..лдат', letter: 'о' },
    { text: 'н..гилист', letter: 'и' },
    { text: 'приор..тет', letter: 'и' },
    { text: 'ф..нансист ', letter: 'и' },
    { text: 'упр..жнение', letter: 'а' },
    { text: 'м..ридиан', letter: 'е' },
    { text: 'ап..льсин', letter: 'е' },
    { text: 'ош..ломлённый', letter: 'е' },
    { text: 'прикр..ватный', letter: 'о' },
    { text: 'шп..онаж', letter: 'и' },
    { text: 'в..стибюль', letter: 'е' },
    { text: 'распроп..гандировать', letter: 'а' },
    { text: 'апл..дировать', letter: 'о' },
    { text: 'арист..крат', letter: 'о' },
    { text: 'к..ндуктор', letter: 'о' },
    { text: 'л..донь', letter: 'а' },
    { text: 'р..акция', letter: 'е' },
    { text: 'в..теран ', letter: 'е' },
    { text: ' проф..риентация', letter: 'о' },
    { text: 'л..песток', letter: 'е' },
    { text: 'д..пломат', letter: 'и' },
    { text: 'през..дент', letter: 'и' },
    { text: 'ижд..венец', letter: 'и' },
    { text: 'п..триотический', letter: 'а' },
    { text: 'т..релка', letter: 'а' },
    { text: 'в..траж', letter: 'и' },
    { text: 'в..ртуоз', letter: 'и' },
    { text: 'предв..рительный', letter: 'а' },
    { text: 'н..стальгия', letter: 'о' },
    { text: 'фл..мастер', letter: 'о' },
    { text: 'в..нтилятор', letter: 'е' },
    { text: 'презид..ум', letter: 'и' },
    { text: 'яг..дный', letter: 'о' },
    { text: 'в..рмишель', letter: 'е' },
    { text: 'ж..лание', letter: 'е' },
    { text: 'зам..розить', letter: 'о' },
    { text: 'ок..лдовать', letter: 'о' },
    { text: 'г..лерея', letter: 'а' },
    { text: 'к..мин', letter: 'а' },
    { text: 'анн..тация', letter: 'о' },
    { text: 'п..ртрет', letter: 'о' },
    { text: 'д..ректор', letter: 'и' },
    { text: 'нотар..ус', letter: 'и' },
    { text: 'тр..ктир', letter: 'а' },
    { text: 'ауд..енция', letter: 'и' },
    { text: 'пр..зидент', letter: 'е' },
    { text: 'пр..вет', letter: 'и' },
    { text: 'т..релка', letter: 'а' },
    { text: 'к..ндидат', letter: 'а' },
    { text: 'к..лач', letter: 'а' },
    { text: 'отв..рять (ворота)', letter: 'о' },
    { text: 'об..няние', letter: 'о' },
]
// B Чередующиеся корни
const typeB = [
    { text: 'покл..ниться', letter: 'о' },
    { text: 'выт..рать', letter: 'и' },
    { text: 'сж..гать', letter: 'и' },
    { text: 'приск..кать', letter: 'а' },
    { text: 'пор..вну', letter: 'о' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'выск..чить', letter: 'о' },
    { text: 'бл..стеть', letter: 'е' },
    { text: 'поч..татель(таланта)', letter: 'и' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'непром..каемый', letter: 'о' },
    { text: 'заг..релый', letter: 'о' },
    { text: 'выч..тание', letter: 'и' },
    { text: 'вл..жения', letter: 'о' },
    { text: 'пл..вник', letter: 'а' },
    { text: 'выр..внять(подлине)', letter: 'о' },
    { text: 'р..стовщик', letter: 'о' },
    { text: 'претв..рить', letter: 'о' },
    { text: 'вск..чить', letter: 'о' },
    { text: 'ст..рать(с доски)', letter: 'е' },
    { text: 'ур..внение', letter: 'а' },
    { text: 'прот..реть', letter: 'е' },
    { text: 'подл..жить', letter: 'о' },
    { text: 'укл..ниться', letter: 'о' },
    { text: 'прекл..нение', letter: 'о' },
    { text: "тв..рить(добро)", letter: "о" },
    { text: "прот..реть(окно)", letter: "е" },
    { text: "выр..с", letter: "о" },
    { text: "пор..сль", letter: "о" },
    { text: "выч..тать(в уме)", letter: "и" },
    { text: "оп..раться", letter: "и" },
    { text: 'пром..кающий', letter: 'о' },
    { text: 'скл..нялся(к мысли)', letter: 'о' },
    { text: 'заг..релый', letter: 'о' },
    { text: 'зам..реть(отвосторга)', letter: 'е' },
    { text: 'поч..тная(грамота)', letter: 'е' },
    { text: 'отр..слевой', letter: 'а' },
    { text: 'выск..чить', letter: 'о' },
    { text: 'ск..чок', letter: 'а' },
    { text: 'спл..вляться(по реке)', letter: 'а' },
    { text: 'зан..маться', letter: 'и' },
    { text: 'поч..татель', letter: 'и' },
    { text: 'прокл..нать', letter: 'и' },
    { text: 'оз..ренный', letter: 'а' },
    { text: 'соч..тание', letter: 'е' },
    { text: "заг..равший", letter: "о" },
    { text: "р..сточек", letter: "о" },
    { text: "ср..внять(счёт)", letter: "а" },
    { text: 'зап..рать (на ключ)', letter: 'и' },
    { text: 'соприк..саться', letter: 'а' },
    { text: 'оп..раясь', letter: 'и' },
    { text: 'выр..сти', letter: 'а' },
    { text: 'р..сток', letter: 'о' },
    { text: 'накл..ниться', letter: 'о' },
    { text: 'вск..чил (на коня)', letter: 'о' },
    { text: 'соб..рёшь', letter: 'е' },
    { text: 'выск..чка', letter: 'о' },
    { text: 'ср..щение ', letter: 'а' },
    { text: 'предпол..жительно', letter: 'о' },
    { text: 'зап..реть ', letter: 'е' },
    { text: 'выск..чка', letter: 'о' },
    { text: 'предпол..жение', letter: 'о' },
    { text: 'зам..реть', letter: 'е' },
    { text: 'к..сательная', letter: 'а' },
    { text: 'пол..гается', letter: 'а' },
    { text: 'забл..стел', letter: 'е' },
    { text: 'ст..лить', letter: 'е' },
    { text: 'з..рница', letter: 'а' },
    { text: 'попл..вок', letter: 'а' },
    { text: 'выр..с', letter: 'о' },
    { text: 'выр..внять (поверхность)', letter: 'о' },
    { text: 'пор..сль', letter: 'р' },
    { text: 'пон..мание', letter: 'и' },
    { text: 'выч..тать (в уме)', letter: 'и' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'м..кать (в молоко)', letter: 'а' },
    { text: 'ур..внение', letter: 'а' },
    { text: 'заб..рать', letter: 'и' },
    { text: 'зар..сли', letter: 'о' },
    { text: 'прик..снуться', letter: 'о' },
    { text: 'предпол..гать', letter: 'а' },
    { text: 'заст..лить', letter: 'е' },
    { text: 'тв..рить', letter: 'л' },
    { text: 'р..весник', letter: 'о' },
    { text: 'р..внение', letter: 'а' },
    { text: 'сг..рание ', letter: 'о' },
    { text: 'оз..риться', letter: 'а' },
    { text: 'к..саться', letter: 'а' },
    { text: 'сл..жившийся', letter: 'о' },
    { text: 'пост..лить', letter: 'е' },
    { text: 'безотл..гательный', letter: 'а' },
    { text: 'подб..рёт', letter: 'е' },
    { text: 'зап..раться', letter: 'и' },
    { text: 'изл..жение', letter: 'о' },
    { text: 'г..релка', letter: 'о' },
    { text: 'сж..гать', letter: 'и' },
    { text: 'напом..нание ', letter: 'и' },
    { text: 'разг..реться', letter: 'о' },
    { text: 'укл..ниться', letter: 'о' },
    { text: 'за́р..сли', letter: 'о' },
    { text: 'з..рница', letter: 'а' },
    { text: 'выл..жить', letter: 'о' },
    { text: 'уб..ру', letter: 'е' },
    { text: 'пл..вец', letter: 'о' },
    { text: 'подг..ревший', letter: 'о' },
    { text: 'расст..лающийся(туман)', letter: 'и' },
    { text: 'расст..лать(скатерть)', letter: 'и' },
    { text: 'выт..реть(стол)', letter: 'и' },
    { text: 'заб..рать', letter: 'и' },
    { text: 'зам..р', letter: 'е' },
    { text: 'изг..рь', letter: 'а' },
    { text: 'пл..вун (грунт)', letter: 'ы' },
    { text: 'к..сательная', letter: 'а' },
    { text: 'пог..релец', letter: 'о' },
    { text: 'выр..с', letter: 'о' },
    { text: 'отр..слевой', letter: 'а' },
    { text: 'ур..вень', letter: 'о' },
    { text: 'заж..мать', letter: 'и' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'прим..рение (сторон)', letter: 'и' },
    { text: 'к..сательная', letter: 'а' },
    { text: 'оз..рение', letter: 'а' },
    { text: 'зар..сли', letter: 'о' },
    { text: 'прик..снуться', letter: 'о' },
    { text: 'изл..жить', letter: 'о' },
    { text: 'несг..раемый', letter: 'о' },
    { text: 'зам..реть', letter: 'е' },
    { text: 'оз..ряться', letter: 'а' },
    { text: 'зап..реть', letter: 'е' },
    { text: 'выст..лить', letter: 'е' },
    { text: 'выск..чка', letter: 'о' },
    { text: 'расст..лается', letter: 'и' },
    { text: 'р..стение', letter: 'а' },
    { text: 'прил..гательное', letter: 'а' },
    { text: 'заст..лать', letter: 'и' },
    { text: 'зап..рать ', letter: 'и' },
    { text: 'з..рница', letter: 'а' },
    { text: 'пром..кнуть (салфеткой)', letter: 'о' },
    { text: 'тв..рительный', letter: 'о' },
    { text: 'пл..вец', letter: 'о' },
    { text: 'прик..снуться', letter: 'о' },
    { text: 'распол..житься', letter: 'о' },
    { text: 'прид..раться', letter: 'и' },
    { text: 'сж..гать', letter: 'и' },
    { text: 'прик..сновение', letter: 'о' },
    { text: 'м..кать (в краску)', letter: 'а' },
    { text: 'бл..стательный', letter: 'и' },
    { text: 'сч..тать', letter: 'и' },
    { text: 'зап..реть', letter: 'е' },
    { text: 'водор..сли', letter: 'о' },
    { text: 'подг..реть', letter: 'о' },
    { text: 'прил..жить', letter: 'о' },
    { text: 'отп..рать', letter: 'и' },
    { text: 'к..сание', letter: 'а' },
    { text: 'р..сток', letter: 'о' },
    { text: 'покл..ниться', letter: 'о' },
    { text: 'нат..реть', letter: 'е' },
    { text: 'р..стение', letter: 'а' },
    { text: 'прил..гательное', letter: 'а' },
    { text: 'ск..кать', letter: 'а' },
    { text: 'подл..жить', letter: 'о' },
    { text: 'ур..внение', letter: 'а' },
    { text: 'прот..реть', letter: 'е' },
    { text: 'сл..жение (чисел)', letter: 'о' },
    { text: 'выск..чка', letter: 'о' },
    { text: 'пл..вчиха', letter: 'о' },
    { text: 'пол..гать', letter: 'а' },
    { text: 'выр..щенный', letter: 'а' },
    { text: 'закл..нать', letter: 'и' },
    { text: 'Р..стов', letter: 'о' },
    { text: 'прим..рять (галстук)', letter: 'е' },
    { text: 'вн..мательный', letter: 'и' },
    { text: 'уб..ру', letter: 'е' },
    { text: 'подб..рёт (цвет)', letter: 'е' },
    { text: 'з..ря', letter: 'а' },
    { text: 'м..кать (в воду)', letter: 'а' },
    { text: 'заст..лить (постель)', letter: 'е' },
    { text: 'обм..кнуть (в краску)', letter: 'а' },
    { text: 'прил..жение', letter: 'о' },
    { text: 'пол..жение', letter: 'о' },
    { text: 'пл..вец', letter: 'о' },
    { text: 'вытв..рять', letter: 'о' },
    { text: 'оп..раясь', letter: 'и' },
    { text: 'раст..рать', letter: 'и' },
    { text: 'выр..внять (пол)', letter: 'о' },
    { text: 'см..чить (водой)', letter: 'о' },
    { text: 'р..стовщик', letter: 'о' },
]
// C Проверяемые корни
const typeC = [
    { text: 'вып..лоть(сорняки)', letter: 'о' },
    { text: 'приг..рюнился', letter: 'о' },
    { text: 'упр..стить', letter: 'о' },
    { text: 'прим..рять(поссорившихся)', letter: 'и' },
    { text: 'ув..жение', letter: 'а' },
    { text: 'поч..нить', letter: 'и' },
    { text: 'ут..плённая(куртка)', letter: 'е' },
    { text: 'прож..вать(пищу)', letter: 'е' },
    { text: "пл..нительный", letter: "е" },
    { text: "объед..нение", letter: "и" },
    { text: "усл..жненный", letter: "о" },
    { text: "др..жать(от холода)", letter: "о" },
    { text: "упр..кать(в скупости)", letter: "е" },
    { text: "зал..зать(надерево)", letter: "е" },
    { text: "хр..брец", letter: "а" },
    { text: "осл..пительный", letter: "е" },
    { text: 'раск..чаться', letter: 'а' },
    { text: 'выв..ска(на двери)', letter: 'е' },
    { text: 'ст..сненное(дыхание)', letter: 'е' },
    { text: '(события)разв..вались', letter: 'и' },
    { text: 'г..ревать', letter: 'о' },
    { text: 'илл..зионист', letter: 'ю' },
    { text: 'разгл..шать', letter: 'а' },
    { text: 'розовощ..кий', letter: 'е' },
    { text: 'землетр..сение', letter: 'я' },
    { text: 'ув..дание(цветов)', letter: 'я' },
    { text: 'ед..номышленник', letter: 'и' },
    { text: 'пот..рять', letter: 'е' },
    { text: 'ст..листический', letter: 'и' },
    { text: 'зап..вал(водой)', letter: 'и' },
    { text: 'л..бединый', letter: 'е' },
    { text: 'обог..щение', letter: 'а' },
    { text: 'нак..лить(докрасна)', letter: 'а' },
    { text: 'г..ристая(местность)', letter: 'о' },
    { text: 'посв..тить(фонарем)', letter: 'е' },
    { text: 'напр..мик', letter: 'я' },
    { text: 'пок..яние', letter: 'а' },
    { text: 'выр..внять(подлине)', letter: 'о' },
    { text: 'тр..петать', letter: 'е' },
    { text: 'амн..стировать', letter: 'и' },
    { text: "см..гчение(нравов)", letter: "я" },
    { text: "х..лмистый", letter: "о" },
    { text: 'пол..скать (бельё)', letter: 'о' },
    { text: 'м..рской', letter: 'о' },
    { text: 'с..неет', letter: 'и' },
    { text: 'п..ровать', letter: 'и' },
    { text: 'ист..щение', letter: 'о' },
    { text: 'препод..вать', letter: 'а' },
    { text: 'уг..сать ', letter: 'а' },
    { text: 'з..мовать', letter: 'и' },
    { text: 'изм..рять', letter: 'е' },
    { text: 'осл..пительный', letter: 'е' },
    { text: 'м..лчание', letter: 'о' },
    { text: 'р..скошный ', letter: 'о' },
    { text: 'соед..нение', letter: 'и' },
    { text: 'разв..ваться (благодаря чтению)', letter: 'и' },
    { text: 'предназн..чение', letter: 'а' },
    { text: 'сокр..щать', letter: 'а' },
    { text: 'д..лина', letter: 'о' },
    { text: 'к..рмить', letter: 'о' },
    { text: 'тр..щать', letter: 'е' },
    { text: 'об..жать (словом)', letter: 'и' },
    { text: 'предст..влять', letter: 'а' },
    { text: 'сп..ртовой (раствор)', letter: 'и' },
    { text: 'энциклоп..дист', letter: 'е' },
    { text: 'ст..лист', letter: 'и' },
    { text: 'разл..новать', letter: 'и' },
    { text: 'разр..дить (всходы)', letter: 'е' },
    { text: 'раск..ли (докрасна)', letter: 'а' },
    { text: 'ух..дить', letter: 'о' },
    { text: 'пок..рять', letter: 'о' },
    { text: 'к..тёнок', letter: 'о' },
    { text: 'хр..брец', letter: 'а' },
    { text: 'осл..пительный', letter: 'е' },
    { text: 'ч..ртить', letter: 'е' },
    { text: 'см..треть', letter: 'о' },
    { text: 'приз..млённый', letter: 'е' },
    { text: 'посв..тил (в темноте)', letter: 'е' },
    { text: 'предск..зание', letter: 'а' },
    { text: 'оскв..рнить', letter: 'е' },
    { text: '(глаза) сл..пались', letter: 'и' },
    { text: 'зап..вать (лекарство)', letter: 'и' },
    { text: 'побл..днел', letter: 'е' },
    { text: 'оч..рование', letter: 'а' },
    { text: 'соед..нение', letter: 'и' },
    { text: 'зат..пить', letter: 'о' },
    { text: 'стр..жайший', letter: 'о' },
    { text: 'приз..млённый', letter: 'е' },
    { text: 'посв..тил (в темноте)', letter: 'е' },
    { text: 'м..льба', letter: 'о' },
    { text: 'скр..пите (листы)', letter: 'е' },
    { text: 'л..сник,', letter: 'е' },
    { text: 'насл..ждение', letter: 'а' },
    { text: 'од..левать (неприятеля)', letter: 'о' },
    { text: 'ув..жение', letter: 'а' },
    { text: 'поч..нить', letter: 'и' },
    { text: 'выл..чить (больного)', letter: 'е' },
    { text: 'тр..петать', letter: 'е' },
    { text: 'запл..тать (косы)', letter: 'е' },
    { text: 'разв..вающийся (флаг)', letter: 'е' },
    { text: 'прим..рять (платье)', letter: 'е' },
    { text: 'восп..вать', letter: 'е' },
    { text: 'вын..с (мусор)', letter: 'е' },
    { text: 'орб..тальный', letter: 'и' },
    { text: 'вызв..лить', letter: 'о' },
    { text: 'упл..тнить', letter: 'о' },
    { text: 'предст..вительный', letter: 'а' },
    { text: 'экз..меновать', letter: 'а' },
    { text: 'асф..льтированный', letter: 'а' },
    { text: 'изд..вать', letter: 'а' },
    { text: 'выстр..ить', letter: 'о' },
    { text: 'пол..мический', letter: 'е' },
    { text: 'непост..жимый', letter: 'и' },
    { text: 'окам..неть', letter: 'е' },
    { text: 'согр..вать', letter: 'е' },
    { text: 'зап..тевать', letter: 'о' },
    { text: 'прив..нтить', letter: 'и' },
    { text: 'скр..пучий', letter: 'и' },
    { text: 'щ..бетать', letter: 'е' },
    { text: 'исст..ри', letter: 'а' },
    { text: 'см..хнуть', letter: 'а' },
    { text: 'ост..новиться', letter: 'а' },
    { text: 'благосл..вить', letter: 'о' },
    { text: 'благосл..вение', letter: 'о' },
    { text: 'ут..хать', letter: 'и' },
    { text: 'скр..вить', letter: 'и' },
    { text: 'скр..петь', letter: 'и' },
    { text: 'скр..петь(на морозе)', letter: 'и' },
    { text: 'ч..стоплотный', letter: 'и' },
    { text: 'ч..столюбивый', letter: 'е' },
    { text: 'ст..листический', letter: 'и' },
    { text: 'ув..дание(цветов)', letter: 'я' },
    { text: 'сист..матизация', letter: 'е' },
    { text: 'стр..мянный', letter: 'е' },
    { text: 'цв..ток', letter: 'е' },
    { text: 'вым..кнуть (под дождём)', letter: 'о' },
    { text: 'зап..роть', letter: 'о' },
    { text: 'вып..сть', letter: 'а' },
    { text: 'обн..жать', letter: 'а' },
    { text: 'отв..рить (овощи)', letter: 'а' },
    { text: 'г..ревать', letter: 'о' },
    { text: 'к..сички ', letter: 'о' },
    { text: 'просм..треть', letter: 'о' },
    { text: 'м..рячок', letter: 'о' },
    { text: 'д..ревья', letter: 'е' },
    { text: 'ум..ротворение', letter: 'и' },
    { text: 'в..дянистый', letter: 'о' },
    { text: 'л..нейка', letter: 'и' },
    { text: 'получ..совой', letter: 'а' },
    { text: 'в..здушный', letter: 'о' },
    { text: 'гр..мыхало', letter: 'о' },
    { text: 'тр..вяной', letter: 'а' },
    { text: 'зас..рять (природу)', letter: 'о' },
    { text: 'перекл..каться', letter: 'и' },
    { text: 'занав..с', letter: 'е' },
    { text: 'запл..сти', letter: 'е' },
    { text: 'дост..ваться', letter: 'а' },
    { text: 'задр..жала', letter: 'о' },
    { text: 'многог..лосье', letter: 'о' },
    { text: 'подсв..тить', letter: 'е' },
    { text: 'ст..кло', letter: 'е' },
    { text: 'передв..жение', letter: 'и' },
    { text: 'г..стевой (дом)', letter: 'о' },
    { text: 'г..лова', letter: 'о' },
    { text: 'об..щавший', letter: 'е' },
    { text: 'подм..гнуть ', letter: 'и' },
    { text: 'подв..ротня', letter: 'о' },
    { text: 'укл..ниться', letter: 'о' },
    { text: 'л..сток', letter: 'и' },
    { text: 'к..вать (головой)', letter: 'и' },
    { text: 'пл..чо', letter: 'е' },
    { text: 'зап..стись (провизией)', letter: 'а' },
    { text: 'непозв..лительно', letter: 'о' },
    { text: 'д..брота', letter: 'о' },
    { text: 'загл..денье', letter: 'я' },
    { text: 'насм..хаться', letter: 'е' },
    { text: 'скр..пучая', letter: 'и' },
    { text: 'пр..лестный', letter: 'е' },
    { text: 'св..сток ', letter: 'и' },
    { text: 'л..тательный (аппарат)', letter: 'е' },
    { text: 'разоч..рованный', letter: 'а' },
    { text: 'выч..сление', letter: 'и' },
    { text: 'к..лючий', letter: 'о' },
    { text: 'скр..пучий', letter: 'и' },
    { text: 'бл..готворительный', letter: 'а' },
    { text: 'к..фейный', letter: 'о' },
    { text: 'ог..рчаться', letter: 'о' },

]
// D Ы/И после приставок
const typeD = [
    { text: 'вз..скать', letter: 'ы' },
    { text: 'без..нициативный', letter: 'ы' },
    { text: 'сверх..зысканный', letter: 'и' },
    { text: 'вз..скание', letter: 'ы' },
    { text: 'без..нтересный', letter: 'ы' },
    { text: 'меж..нститутский', letter: 'и' },
    { text: 'сверх..зысканно', letter: 'и' },
    { text: 'меж..здательский', letter: 'и' },
    { text: 'пред..дущий', letter: 'ы' },
    { text: 'от..скать', letter: 'ы' },
    { text: 'пост..ндустриальный', letter: 'и' },
    { text: 'за..нтересовать', letter: 'и' },
    { text: 'с..митировать', letter: 'ы' },
    { text: 'без..сходный', letter: 'ы' },
    { text: 'под..грать', letter: 'ы' },
    { text: 'роз..грыш', letter: 'ы' },
    { text: 'без..скусный', letter: 'ы' },
    { text: 'за..граться', letter: 'и' },
    { text: 'без..ндукционный', letter: 'ы' },
    { text: 'меж..гровой', letter: 'и' },
    { text: 'с..мпровизировать', letter: 'ы' },
    { text: 'из..скать', letter: 'ы' },
    { text: 'пред..стория', letter: 'ы' },
    { text: 'сверх..скусный', letter: 'и' },
    { text: 'вз..скать', letter: 'ы' },
    { text: 'роз..грыш', letter: 'ы' },
    { text: 'супер..гра', letter: 'и' },
    { text: 'от..мённое (прилагательное)', letter: 'ы' },
    { text: 'раз..грать', letter: 'ы' },
    { text: 'воз..меть', letter: 'ы' },
    { text: 'сверх..зысканно', letter: 'и' },
    { text: 'пред..юньский', letter: 'ы' },
    { text: 'без..нициативный', letter: 'ы' },
    { text: 'вз..скать', letter: 'ы' },
    { text: 'роз..грыш', letter: 'ы' },
    { text: 'под..грать', letter: 'ы' },
    { text: 'пред..нфарктное (состояние)', letter: 'ы' },
    { text: 'меж..нститутский', letter: 'и' },
    { text: 'спорт..нвентарь', letter: 'и' },
    { text: 'сверх..зысканно', letter: 'и' },
    { text: 'меж..нститутский ', letter: 'и' },

]
// E Ъ/Ь после приставок
const typeE = [
    { text: 'под..езд', letter: 'ъ' },
    { text: 'сверх..естественный', letter: 'ъ' },
    { text: 'с..ёмка', letter: 'ъ' },
    { text: 'двух..ярусный', letter: 'ъ' },
    { text: 'зав..южило', letter: 'ь' },
    { text: 'фамил..ярный', letter: 'ь' },
    { text: 'гнездов..е', letter: 'ь' },
    { text: 'с..ёжился', letter: 'ъ' },
    { text: 'в..едливый', letter: 'ъ' },
    { text: 'б..ющийся', letter: 'ь' },
    { text: 'пред..юбилейный', letter: 'ъ' },
    { text: 'раз..ярённый', letter: 'ъ' },
    { text: 'кур..ёз', letter: 'ь' },
    { text: 'без..нициативный', letter: 'ы' },
    { text: 'с..язвить', letter: 'ъ' },
    { text: 'в..юга', letter: 'ь' },
    { text: 'ад..ютант', letter: 'ъ' },
    { text: 'в..юнок', letter: 'ь' },
    { text: 'меж..ярусный', letter: 'ъ' },
    { text: 'ад..ютант', letter: 'ъ' },
    { text: 'в..юнок', letter: 'ь' },
    { text: 'меж..ярусный', letter: 'ъ' },
    { text: 'ад..ютант', letter: 'ъ' },
    { text: 'фельд..егерь', letter: 'ъ' },
    { text: 'из..ян', letter: 'ъ' },
    { text: 'под..езд', letter: 'ъ' },
    { text: 'с..ёжиться', letter: 'ъ' },
    { text: 'под..язычный', letter: 'ъ' },
    { text: 'об..ездной', letter: 'ъ' },
    { text: 'пред..юбилейный', letter: 'ъ' },
    { text: 'об..ёмный', letter: 'ъ' },
    { text: 'в..юга', letter: 'ь' },
    { text: 'вз..ерошить', letter: 'ъ' },
    { text: 'пред..юбилейный', letter: 'ъ' },
    { text: 'об..ект', letter: 'ъ' },
    { text: 'транс..европейский', letter: 'ъ' },
    { text: 'об..ектив (камеры)', letter: 'ъ' },
    { text: 'двух..ярусный', letter: 'ъ' },
    { text: 'из..сканный', letter: 'ы' },
    { text: 'от..грывать', letter: 'ы' },
    { text: 'пред..дущий', letter: 'ы' },
]
// F Гласные и согласные в приставках
const typeF = [
    { text: 'пр..образовать', letter: 'е' },
    { text: 'пр..неприятный', letter: 'е' },
    { text: 'пр..следовать', letter: 'е' },
    { text: 'п..никнуть', letter: 'о' },
    { text: 'пр..дедушка', letter: 'а' },
    { text: 'поз..вчера', letter: 'а' },
    { text: 'чере..чур', letter: 'с' },
    { text: 'и..синя-чёрный', letter: 'с' },
    { text: 'бе..крайний', letter: 'с' },
    { text: 'пр..добрый', letter: 'е' },
    { text: 'гостепр..имный', letter: 'и' },
    { text: 'правопр..емник', letter: 'е' },
    { text: 'н..дломить', letter: 'а' },
    { text: 'поз..бросил', letter: 'а' },
    { text: 'з..ночевать', letter: 'а' },
    { text: 'бе..срочный', letter: 'с' },
    { text: 'и..черченный', letter: 'с' },
    { text: 'ра..пущенный', letter: 'с' },
    { text: 'ра..буженный', letter: 'з' },
    { text: 'бе..граничный', letter: 'з' },
    { text: 'и..вестить', letter: 'з' },
    { text: 'н..испособнейший', letter: 'а' },
    { text: 'поз..вчера', letter: 'а' },
    { text: 'н..дстройка', letter: 'а' },
    { text: 'пр..следовать (врага)', letter: 'е' },
    { text: 'пр..купить', letter: 'и' },
    { text: 'пр..шить (пуговицу)', letter: 'и' },
    { text: 'по..черкнуть', letter: 'д' },
    { text: 'на..пись', letter: 'д' },
    { text: 'пре..писание', letter: 'д' },
    { text: 'пр..стыдить', letter: 'и' },
    { text: 'непр..ступная (крепость)', letter: 'и' },
    { text: 'беспр..мерный', letter: 'и' },
    { text: 'сни..хождение', letter: 'с' },
    { text: 'и..колесить', letter: 'с' },
    { text: 'ра..ценки', letter: 'с' },
    { text: 'непре..сказуемый', letter: 'д' },
    { text: 'о..блеск', letter: 'т' },
    { text: 'по..точить', letter: 'д' },
    { text: 'нер..ссказанный', letter: 'а' },
    { text: 'под..спел', letter: 'о' },
    { text: 'н..илучший', letter: 'а' },
    { text: 'пр..землиться', letter: 'и' },
    { text: 'пр..обретение', letter: 'и' },
    { text: 'пр..открывшийся', letter: 'и' },
    { text: 'р..зобщённо', letter: 'а' },
    { text: 'п..переменно', letter: 'о' },
    { text: 'пр..верка', letter: 'о' },
    { text: 'ра..мешать', letter: 'з' },
    { text: 'бе..граничный', letter: 'з' },
    { text: 'бе..численный', letter: 'с' },
    { text: 'пр..бинтовать', letter: 'и' },
    { text: 'пр..морский', letter: 'и' },
    { text: 'пр..бывать (на станцию)', letter: 'и' },
    { text: 'по..цепленный (вагон)', letter: 'д' },
    { text: 'о..гадать', letter: 'т' },
    { text: 'на..кусить', letter: 'д' },
    { text: 'ра..сеять', letter: 'с' },
    { text: 'в..балтывать', letter: 'з' },
    { text: 'бе..голосый', letter: 'з' },
    { text: 'непр..будный', letter: 'о' },
    { text: 'нед..варить', letter: 'о' },
    { text: 'п..завчера', letter: 'о' },
    { text: 'в..скликнул', letter: 'о' },
    { text: 'п..дножие (горы)', letter: 'о' },
    { text: 'об..льстить', letter: 'о' },
    { text: 'пр..стройка', letter: 'и' },
    { text: 'непр..рывный', letter: 'е' },
    { text: 'пр..станище', letter: 'и' },
    { text: 'не..добровать', letter: 'с' },
    { text: 'ра..колоть', letter: 'с' },
    { text: 'бе..принципный', letter: 'с' },
    { text: 'бе..характерный', letter: 'с' },
    { text: 'ра..хваливать', letter: 'с' },
    { text: 'и..пытывать', letter: 'с' },
    { text: 'д..гнать', letter: 'о' },
    { text: 'пр..анализировать', letter: 'о' },
    { text: 'вз..браться', letter: 'о' },
    { text: 'пр..ложение', letter: 'и' },
    { text: 'пр..озёрный', letter: 'и' },
    { text: 'непр..миримый', letter: 'и' },
    { text: 'пер..лёт', letter: 'е' },
    { text: 'ант..военный', letter: 'и' },
    { text: 'н..дооценивать', letter: 'е' },
    { text: 'обе..доленный', letter: 'з' },
    { text: 'чере..чур', letter: 'с' },
    { text: 'не..держанный', letter: 'с' },
    { text: 'пр..бить (гвоздь)', letter: 'и' },
    { text: 'пр..клеить (на бумагу)', letter: 'и' },
    { text: 'пр..брежный', letter: 'и' },
    { text: 'арх..важный', letter: 'и' },
    { text: 'ант..художественный', letter: 'и' },
    { text: 'д..сквалификация', letter: 'и' },
    { text: 'поз..прошлый (год)', letter: 'а' },
    { text: 'с..путствовать', letter: 'о' },
    { text: 'р..зослать (письма)', letter: 'а' },
    { text: 'нед..верчивый', letter: 'о' },
    { text: 'п..дорожник', letter: 'о' },
    { text: 'нен..глядный', letter: 'а' },
    { text: 'пр..мета', letter: 'и' },
    { text: 'непр..годный', letter: 'и' },
    { text: 'пр..стройка', letter: 'и' },
    { text: 'и..брать', letter: 'з' },
    { text: 'и..желта-красный', letter: 'з' },
    { text: 'бе..вестный', letter: 'з' },
    { text: 'пр..карманить', letter: 'и' },
    { text: 'пр..терпеться (к боли)', letter: 'и' },
    { text: 'пр..уныл', letter: 'и' },
    { text: 'пре..написанное', letter: 'д' },
    { text: 'на..кусил', letter: 'д' },
    { text: 'по..править', letter: 'д' },
    { text: 'не..держанный', letter: 'с' },
    { text: 'и..бежать', letter: 'з' },
    { text: 'во..препятствовать', letter: 'с' },
    { text: 'не..глядный', letter: 'о' },
    { text: 'от..бравший', letter: 'о' },
    { text: 'запр..кинуть', letter: 'о' },
    { text: 'пре..писание', letter: 'д' },
    { text: 'на..кусить', letter: 'д' },
    { text: 'по..править', letter: 'д' },
    { text: 'бе..компромиссный', letter: 'с' },
    { text: 'во..росший', letter: 'з' },
    { text: 'не..держанный', letter: 'с' },
    { text: 'пр..брежный', letter: 'и' },
    { text: 'пр..терпеться (к боли)', letter: 'и' },
    { text: 'пр..уныть', letter: 'и' },
    { text: 'под..брать', letter: 'о' },
    { text: 'нез..вершённая (работа)', letter: 'а' },
    { text: 'п..немногу', letter: 'о' },
    { text: 'пр..рывистое (движение)', letter: 'е' },
    { text: 'пр..следовать (нарушителя)', letter: 'е' },
    { text: 'пр..емственность', letter: 'е' },
    { text: '(всероссийские) ..дравницы', letter: 'з' },
    { text: 'обе..главить', letter: 'з' },
    { text: 'во..даяние', letter: 'з' },
    { text: 'в..зомнить', letter: 'о' },
    { text: 'пред..ставить', letter: 'о' },
    { text: 'з..облачные (цены)', letter: 'а' },
    { text: 'пре..приниматель', letter: 'д' },
    { text: 'по..сказка (в загадке)', letter: 'д' },
    { text: 'на..кусить', letter: 'д' },
    { text: 'пр..нарядиться', letter: 'и' },
    { text: 'пр..школьный', letter: 'и' },
    { text: 'пр..шелец', letter: 'и' },
    { text: 'бе..помощный', letter: 'с' },
    { text: 'ни..провержение', letter: 'с' },
    { text: 'ра..счёт', letter: 'с' },
    { text: 'п..дпустить', letter: 'о' },
    { text: 'не..хватный', letter: 'о' },
    { text: 'в..зместить', letter: 'о' },
    { text: 'обе..доленный', letter: 'з' },
    { text: '*чере..чур', letter: 'с' },
    { text: 'не..держанный', letter: 'с' },
    { text: 'пр..бить (гвоздь)', letter: 'и' },
    { text: 'пр..клеить (на бумагу)', letter: 'и' },
    { text: 'пр..брежный', letter: 'и' },
    { text: 'пр..бабушка', letter: 'а' },
    { text: 'пр..язык', letter: 'а' },
    { text: 'пр..родина', letter: 'а' },
    { text: 'поз..прошлый (год)', letter: 'а' },
    { text: 'с..путствовать', letter: 'о' },
    { text: 'р..зослать (письма)', letter: 'а' },
    { text: 'по..веска (с изумрудом)', letter: 'д' },
    { text: 'на..ставить (платье)', letter: 'д' },
    { text: 'пре..защита (диссертации)', letter: 'д' },
    { text: 'пр..станище', letter: 'и' },
    { text: 'пр..стыдил (друга)', letter: 'и' },
    { text: 'пр..волье (вокруг)', letter: 'и' },
    { text: 'не..добный (пирог)', letter: 'с' },
    { text: 'ра..гореться', letter: 'з' },
    { text: 'во..держание (от пищи)', letter: 'з' },
    { text: '(включить) пр..ёмник', letter: 'и' },
    { text: 'пр..старелый (отец)', letter: 'е' },
    { text: 'пр..дорожный', letter: 'и' },
    { text: 'з..рубежный', letter: 'а' },
    { text: 'пр..родина', letter: 'а' },
    { text: 'н..пример', letter: 'а' },
    { text: 'не..добровать', letter: 'с' },
    { text: 'ра..красить', letter: 'с' },
    { text: 'бе.. вкусный', letter: 'з' },
    { text: 'пр..даваться (веселью)', letter: 'е' },
    { text: 'пр..емственность', letter: 'е' },
    { text: 'пр..ступник', letter: 'е' },
    { text: 'по..метить', letter: 'д' },
    { text: 'на..ломленный', letter: 'д' },
    { text: 'о..дежурить', letter: 'т' },
    { text: 'бе..земельный', letter: 'з' },
    { text: 'и..портить', letter: 'с' },
    { text: 'ни..посланный', letter: 'с' },
    { text: 'пр..горелый', letter: 'и' },
    { text: 'пр..обрести', letter: 'и' },
    { text: 'пр..открытый', letter: 'и' },
    { text: 'п..переменно', letter: 'о' },
    { text: 'пр..студа', letter: 'о' },
    { text: 'р..зровнять ', letter: 'а' },
    { text: 'ра..мешать', letter: 'з' },
    { text: 'бе..граничный', letter: 'з' },
    { text: 'и..рисованный ', letter: 'з' },
    { text: 'пр..землиться', letter: 'и' },
    { text: 'пр..обретение', letter: 'и' },
    { text: 'пр..открывшийся ', letter: 'и' },
    { text: 'пр..двзятый', letter: 'е' },
    { text: 'н..зводить', letter: 'и' },
    { text: 'н..сходящий', letter: 'и' },
]
// G Е/О после шипящих
const typeG = [
    { text: "полуш..пот", letter: "е" },
    { text: 'деш..вый', letter: 'е' },
    { text: "пощ..чина", letter: "е" },
    { text: '(рассказывать)ш..потом', letter: 'е' },
    { text: 'щ..тка', letter: 'е' },
]
// экспорт
export { typeA, typeB, typeC, typeD, typeE, typeF, typeG }