// A Словарные слова
const typeA = [
    { text: 'г..потеза', letter: 'и' },
    { text: 'г..роизм', letter: 'е' },
    { text: 'к..мпонент', letter: 'о' },
    { text: 'альм..нах', letter: 'а' },
    { text: "р..квизит", letter: "е" },
    { text: "р..комендовать", letter: "е" },
    { text: "р..кошет", letter: "и" },
    { text: "р..естр", letter: "е" },
    { text: "р..жим", letter: "е" },
    { text: "р..жиссер", letter: "е" },
    { text: "с..нтиментальный", letter: "е" },
    { text: "с..нхронный", letter: "и" },
    { text: "сп..ртакиада", letter: "а" },
    { text: "ср..внять", letter: "а" },
    { text: "полуш..пот", letter: "е" },
    { text: "пощ..чина", letter: "е" },
    { text: "заг..равший", letter: "о" },
    { text: "р..сточек", letter: "о" },
    { text: "рест..врация", letter: "а" },
    { text: "инт..ллектуальный", letter: "е" },
    { text: "предс..датель", letter: "е" },
    { text: "сб..режения", letter: "е" },
    { text: "обр..млять(гравюру)", letter: "а" },
    { text: "х..лмистый", letter: "о" },
    { text: "п..лемический", letter: "о" },
    { text: "см..гчение(нравов)", letter: "я" },
    { text: "разъ..снение", letter: "я" },
    { text: "см..калистый(ученик)", letter: "е" },
    { text: "д..лина", letter: "о" },
    { text: "м..хнатый", letter: "о" },
    { text: "подор..жание", letter: "о" },
    { text: "иск..жать(смысл)", letter: "а" },
    { text: "др..жать(от холода)", letter: "о" },
    { text: "энц..клопедия", letter: "и" },
    { text: "ц..линдр", letter: "и" },
    { text: "ц..ганский", letter: "ы" },
    { text: "пл..нительный", letter: "е" },
    { text: "р..форма", letter: "е" },
    { text: "объед..нение", letter: "и" },
    { text: "усл..жненный", letter: "о" },
    { text: "анн..тация", letter: "о" },
    { text: "тв..рить(добро́)", letter: "о" },
    { text: "упр..кать(вскупости)", letter: "е" },
    { text: "прот..реть(окно)", letter: "е" },
    { text: "зал..зать(надерево)", letter: "е" },
    { text: "г..строном", letter: "а" },
    { text: "хр..брец", letter: "а" },
    { text: "к..бинет", letter: "а" },
    { text: "р..гулировать", letter: "е" },
    { text: "д..легат", letter: "е" },
    { text: "д..сциплина", letter: "и" },
    { text: "выр..с", letter: "о" },
    { text: "выр..внять(поверхность)", letter: "о" },
    { text: "пор..сль", letter: "о" },
    { text: "р..зультат", letter: "е" },
    { text: "в..негрет", letter: "и" },
    { text: "осл..пительный", letter: "е" },
    { text: "пон..мание", letter: "и" },
    { text: "выч..тать(вуме)", letter: "и" },
    { text: "оп..раться", letter: "и" },
    { text: 'раск..чаться', letter: 'а' },
    { text: 'пром..кающий', letter: 'о' },
    { text: 'предл..жение', letter: 'о' },
    { text: 'зап..вать(водой)', letter: 'и' },
    { text: 'усм..ренный', letter: 'и' },
    { text: 'поч..тать(старших)', letter: 'и' },
    { text: 'б..ллетень', letter: 'ю' },
    { text: 'параш..т', letter: 'ю' },
    { text: '(члены)ж..ри', letter: 'ю' },
    { text: 'выв..ска(на двери)', letter: 'е' },
    { text: 'ош..ломленный', letter: 'е' },
    { text: 'разб..гатеть', letter: 'о' },
    { text: '(молодая)пор..сль(кустов)', letter: 'о' },
    { text: 'провозгл..шать', letter: 'а' },
    { text: 'к..рифей', letter: 'о' },
    { text: 'скл..нялся(кмысли)', letter: 'о' },
    { text: 'заг..релый', letter: 'о' },
    { text: 'зам..реть(отвосторга)', letter: 'е' },
    { text: 'дел..катес', letter: 'и' },
    { text: 'ст..сненное(дыхание)', letter: 'е' },
    { text: 'панц..рь', letter: 'и' },
    { text: 'рац..ональный', letter: 'и' },
    { text: 'ц..вилизация', letter: 'и' },
    { text: 'просв..щение', letter: 'е' },
    { text: 'инт..ллект', letter: 'е' },
    { text: 'конт..нент', letter: 'и' },
    { text: 'сост..зание', letter: 'я' },
    { text: 'у..звить', letter: 'я' },
    { text: 'см..тение', letter: 'я' },
    { text: 'интелл..гентный', letter: 'и' },
    { text: '(события)разв..вались', letter: 'и' },
    { text: 'щ..тка', letter: 'е' },
    { text: 'поч..тная(грамота)', letter: 'е' },
    { text: '(рассказывать)ш..потом', letter: 'е' },
    { text: 'г..ревать', letter: 'о' },
    { text: 'насл..ждение', letter: 'а' },
    { text: 'рест..врация', letter: 'а' },
    { text: 'брош..ра', letter: 'ю' },
    { text: 'параш..тный', letter: 'ю' },
    { text: 'абаж..р', letter: 'у' },
    { text: 'отр..слевой', letter: 'а' },
    { text: 'об..ятельный', letter: 'а' },
    { text: 'симп..тичный', letter: 'а' },
    { text: 'ал..миний', letter: 'ю' },
    { text: 'б..ллетень', letter: 'ю' },
    { text: 'илл..зионист', letter: 'ю' },
    { text: 'погл..щать', letter: 'о' },
    { text: 'разгл..шать', letter: 'а' },
    { text: 'выск..чить', letter: 'о' },
    { text: 'вент..лятор', letter: 'и' },
    { text: 'верм..шель', letter: 'и' },
    { text: 'приподн..мать', letter: 'и' },
    { text: 'ск..чок', letter: 'а' },
    { text: 'непром..каемый', letter: 'о' },
    { text: 'спл..вляться(пореке)', letter: 'а' },
    { text: 'расч..т', letter: 'е' },
    { text: 'реш..тка', letter: 'е' },
    { text: 'розовощ..кий', letter: 'е' },
    { text: 'ув..дание(цветов)', letter: 'я' },
    { text: 'землетр..сение', letter: 'я' },
    { text: 'об..зательно', letter: 'я' },
    { text: 'исп..лнение', letter: 'о' },
    { text: 'в..рсистый', letter: 'о' },
    { text: 'прекл..нение', letter: 'о' },
    { text: 'тр..нажер', letter: 'е' },
    { text: 'ед..номышленник', letter: 'и' },
    { text: 'пот..рять', letter: 'е' },
    { text: 'ст..листический', letter: 'и' },
    { text: 'зан..маться', letter: 'и' },
    { text: 'ч..стоплотный', letter: 'и' },
    { text: 'г..роизм', letter: 'е' },
    { text: 'зап..вал(водой)', letter: 'и' },
    { text: 'л..бединый', letter: 'е' },
    { text: 'к..ртон', letter: 'а' },
    { text: 'обог..щение', letter: 'а' },
    { text: 'п..риод', letter: 'е' },
    { text: '(ударился)оз..мь', letter: 'е' },
    { text: 'оф..цер', letter: 'и' },
    { text: 'поч..татель', letter: 'и' },
    { text: 'прокл..нать', letter: 'и' },
    { text: 'б..хрома', letter: 'а' },
    { text: 'оз..ренный', letter: 'а' },
    { text: 'нак..лить(докрасна)', letter: 'а' },
    { text: 'экстр..мальный', letter: 'е' },
    { text: 'соч..тание', letter: 'е' },
    { text: 'раст..рзать', letter: 'е' },
    { text: 'н..гилист', letter: 'и' },
    { text: 'приор..тет', letter: 'и' },
    { text: 'ф..нансист', letter: 'и' },
    { text: 'упр..жнение', letter: 'а' },
    { text: 'подв..ротня', letter: 'о' },
    { text: 'укл..ниться', letter: 'о' },
    { text: 'м..ридиан', letter: 'е' },
    { text: 'ап..льсин', letter: 'е' },
    { text: 'ош..ломленный', letter: 'е' },
    { text: 'прикр..ватный', letter: 'о' },
    { text: 'подл..жить', letter: 'о' },
    { text: 'ур..внение', letter: 'а' },
    { text: 'прот..реть', letter: 'е' },
    { text: 'л..сток', letter: 'и' },
    { text: 'к..вать(головой)', letter: 'и' },
    { text: 'велос..пед', letter: 'и' },
    { text: 'галакт..ка', letter: 'и' },
    { text: 'ст..рать(сдоски)', letter: 'е' },
    { text: 'вск..чить', letter: 'о' },
    { text: 'к..мфорт', letter: 'о' },
    { text: 'п..лировать(мебель)', letter: 'о' },
    { text: 'н..циональный', letter: 'а' },
    { text: 'пок..ситься(отстарости)', letter: 'о' },
    { text: 'в..кзал', letter: 'о' },
    { text: 'претв..рить', letter: 'о' },
    { text: 'г..ристая(местность)', letter: 'о' },
    { text: 'к..ллекционный', letter: 'о' },
    { text: 'потр..сающий', letter: 'я' },
    { text: 'посв..тить(фонарем)', letter: 'е' },
    { text: 'напр..мик', letter: 'я' },
    { text: 'ш..винизм', letter: 'о' },
    { text: 'ш..ковый', letter: 'ё' },
    { text: 'ш..мпол', letter: 'о' },
    { text: 'р..стовщик', letter: 'о' },
    { text: 'отр..сль', letter: 'а' },
    { text: 'укр..щавший(тигра)', letter: 'о' },
    { text: 'ярм..рка', letter: 'а' },
    { text: 'выр..внять(подлине)', letter: 'о' },
    { text: 'пок..яние', letter: 'а' },
    { text: 'скр..пя(сердце)', letter: 'е' },
    { text: 'тр..петать', letter: 'е' },
    { text: 'пос..деть(кстарости)', letter: 'е' },
    { text: 'просв..щение', letter: 'е' },
    { text: 'пл..вник', letter: 'а' },
    { text: 'п..ркет', letter: 'а' },
    { text: 'вл..жения', letter: 'о' },
    { text: 'г..рняцкий', letter: 'о' },
    { text: 'погл..щение', letter: 'о' },
    { text: 'об..няние', letter: 'о' },
    { text: 'прид..ржать', letter: 'и' },
    { text: 'амн..стировать', letter: 'и' },
    { text: 'ид..ологический', letter: 'е' },
    { text: 'ч..столюбие', letter: 'е' },
    { text: 'выч..тание', letter: 'и' },
    { text: 'зан..мательный', letter: 'и' },
    { text: 'отв..рить(дверь)', letter: 'о' },
    { text: 'подск..чить', letter: 'о' },
    { text: 'зак..снелый', letter: 'о' },
    { text: 'заг..релый', letter: 'о' },
    { text: 'непром..каемый', letter: 'о' },
    { text: 'к..мендант', letter: 'о' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'см..нать(траву)', letter: 'и' },
    { text: 'поч..татель(таланта)', letter: 'и' },
    { text: 'укр..титель(тигров)', letter: 'о' },
    { text: 'симп..тичный', letter: 'а' },
    { text: 'посв..щение(другу)', letter: 'я' },
    { text: 'недос..гаемый', letter: 'и' },
    { text: 'у..звить', letter: 'я' },
    { text: 'бл..стеть', letter: 'е' },
    { text: 'с..дина(вволосах)', letter: 'е' },
    { text: 'прим..рять(поссорившихся)', letter: 'и' },
    { text: 'стр..жайший', letter: 'о' },
    { text: 'упр..стить', letter: 'о' },
    { text: 'приг..рюнился', letter: 'о' },
    { text: 'подб..родок', letter: 'о' },
    { text: 'к..стюмер', letter: 'о' },
    { text: 'ув..жение', letter: 'а' },
    { text: 'поч..нить', letter: 'и' },
    { text: '(ударился)оз..мь', letter: 'е' },
    { text: 'см..ренный', letter: 'и' },
    { text: 'расч..ртить', letter: 'е' },
    { text: 'встр..чаемся', letter: 'е' },
    { text: '(крепкая)б..чёвка', letter: 'е' },
    { text: 'покл..ниться', letter: 'о' },
    { text: 'пропол..скать(бельё)', letter: 'о' },
    { text: 'г..ризонтальный', letter: 'о' },
    { text: 'разб..раться', letter: 'и' },
    { text: 'выт..рать', letter: 'и' },
    { text: 'сж..гать', letter: 'и' },
    { text: 'нач..нать', letter: 'и' },
    { text: 'п..рила', letter: 'е' },
    { text: 'распл..скать', letter: 'е' },
    { text: 'соч..тание', letter: 'е' },
    { text: 'пор..вну', letter: 'о' },
    { text: 'приск..кать', letter: 'а' },
    { text: 'возл..гать', letter: 'а' },
    { text: 'опров..ргать', letter: 'е' },
    { text: 'д..баты', letter: 'е' },
    { text: 'ист..нный', letter: 'и' },
    { text: 'б..рлога', letter: 'е' },
    { text: 'п..лотируемый', letter: 'и' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'глоб..листский', letter: 'а' },
    { text: 'к..раллы', letter: 'о' },
    { text: 'вып..лоть(сорняки)', letter: 'о' },
    { text: 'ос..бняк', letter: 'о' },
    { text: 'т..рговец', letter: 'о' },
    { text: 'об..грённый(кровью)', letter: 'а' },
    { text: 'м..заичный', letter: 'о' },
    { text: 'выск..чить', letter: 'о' },
    { text: 'в..пиющий(случай)', letter: 'о' },
    { text: 'прож..вать(пищу)', letter: 'е' },
    { text: 'ут..плённая(куртка)', letter: 'е' },
    { text: 'д..сантироваться', letter: 'е' },
    { text: '..нчоус', letter: 'а' },
    { text: '..укцион', letter: 'а' },
    { text: 'апп..тит', letter: 'е' },
    { text: 'р..гламент', letter: 'е' },
    { text: 'ав..нгард', letter: 'а' },
    { text: 'п..рила', letter: 'е' },
    { text: 'ар..стократ', letter: 'и' },
    { text: 'м..нистерство', letter: 'и' },
    { text: 'д..визион', letter: 'и' },
    { text: 'г..ризонт', letter: 'о' },
    { text: 'стр..тегия', letter: 'а' },
    { text: 'пр..оритет', letter: 'и' },
    { text: 'к..мфорт', letter: 'о' },
    { text: 'сп..раль', letter: 'и' },
    { text: 'б..рашек', letter: 'а' },
    { text: 'ф..рмат', letter: 'о' },
    { text: 'предв..рительный', letter: 'а' },
    { text: 'прид..рожный', letter: 'о' },
    { text: 'доск..нально', letter: 'о' },
    { text: 'б..лото', letter: 'о' },
    { text: 'нест..бильно', letter: 'а' },
    { text: 'ш..девр', letter: 'е' },
    { text: 'д..визия', letter: 'и' },
    { text: 'с..лдат', letter: 'о' },
    { text: 'н..гилист', letter: 'и' },
    { text: 'приор..тет', letter: 'и' },
    { text: 'ф..нансист ', letter: 'и' },
    { text: 'упр..жнение', letter: 'а' },
    { text: 'м..ридиан', letter: 'е' },
    { text: 'ап..льсин', letter: 'е' },
    { text: 'ош..ломлённый', letter: 'е' },
    { text: 'прикр..ватный', letter: 'о' },
    { text: 'шп..онаж', letter: 'и' },
    { text: 'в..стибюль', letter: 'е' },
    { text: 'распроп..гандировать', letter: 'а' },
    { text: 'апл..дировать', letter: 'о' },
    { text: 'арист..крат', letter: 'о' },
    { text: 'к..ндуктор', letter: 'о' },
    { text: 'л..донь', letter: 'а' },
    { text: 'р..акция', letter: 'е' },
    { text: 'в..теран ', letter: 'е' },
    { text: ' проф..риентация', letter: 'о' },
    { text: 'л...песток', letter: 'е' },
    { text: 'д..пломат', letter: 'и' },
    { text: 'през..дент', letter: 'и' },
    { text: 'ижд..венец', letter: 'и' },
    { text: 'п..триотический', letter: 'а' },
    { text: 'т..релка', letter: 'а' },
    { text: 'в..траж', letter: 'и' },
    { text: 'в..ртуоз', letter: 'и' },
    { text: 'предв..рительный', letter: 'а' },
    { text: 'н..стальгия', letter: 'о' },
    { text: 'фл..мастер', letter: 'о' },
    { text: 'в..нтилятор', letter: 'е' },
    { text: 'презид..ум', letter: 'и' },
    { text: 'яг..дный', letter: 'о' },
    { text: 'в..рмишель', letter: 'е' },
    { text: 'ж..лание', letter: 'е' },
    { text: 'зам..розить', letter: 'о' },
    { text: 'ок..лдовать', letter: 'о' },
    { text: 'г..лерея', letter: 'а' },
    { text: 'к..мин', letter: 'а' },
    { text: 'анн..тация', letter: 'о' },
    { text: 'п..ртрет', letter: 'о' },
    { text: 'д..ректор', letter: 'и' },
    { text: 'нотар..ус', letter: 'и' },
    { text: 'тр..ктир', letter: 'а' },
    { text: 'ауд..енция', letter: 'и' },
    { text: 'пр..зидент', letter: 'е' },
    { text: 'пр..вет', letter: 'и' },
    { text: 'т..релка', letter: 'а' },
    { text: 'к..ндидат', letter: 'а' },
    { text: 'к..лач', letter: 'а' },
    { text: 'отв..рять (ворота)', letter: 'о' },
    { text: 'об..няние', letter: 'о' },
]
// B Чередующиеся корни
const typeB = [
    { text: 'подг..ревший', letter: 'о' },
    { text: 'расст..лающийся(туман)', letter: 'и' },
    { text: 'расст..лать(скатерть)', letter: 'и' },
    { text: 'выт..реть(стол)', letter: 'и' },
    { text: 'заб..рать', letter: 'и' },
    { text: 'зам..р', letter: 'е' },
    { text: 'изг..рь', letter: 'а' },
    { text: 'пл..вун (грунт)', letter: 'ы' },
    { text: 'к..сательная', letter: 'а' },
    { text: 'пог..релец', letter: 'о' },
    { text: 'выр..с', letter: 'о' },
    { text: 'отр..слевой', letter: 'а' },
    { text: 'ур..вень', letter: 'о' },
    { text: 'заж..мать', letter: 'и' },
    { text: 'оп..раться', letter: 'и' },
    { text: 'прим..рение (сторон)', letter: 'и' },
    { text: 'к..сательная', letter: 'а' },
    { text: 'оз..рение', letter: 'а' },
    { text: 'зар..сли', letter: 'о' },
    { text: 'прик..снуться', letter: 'о' },
    { text: 'изл..жить', letter: 'о' },
    { text: 'несг..раемый', letter: 'о' },
    { text: 'зам..реть', letter: 'е' },
    { text: 'оз..ряться', letter: 'а' },
    { text: 'зап..реть', letter: 'е' },
    { text: 'выст..лить', letter: 'е' },
    { text: 'выск..чка', letter: 'о' },
    { text: 'расст..лается', letter: 'и' },
    { text: 'р..стение', letter: 'а' },
    { text: 'прил..гательное', letter: 'а' },
    { text: 'заст..лать', letter: 'и' },
    { text: 'зап..рать ', letter: 'и' },
    { text: 'з..рница', letter: 'а' },
    { text: 'пром..кнуть (салфеткой)', letter: 'о' },
    { text: 'тв..рительный', letter: 'о' },
    { text: 'пл..вец', letter: 'о' },
    { text: 'прик..снуться', letter: 'о' },
    { text: 'распол..житься', letter: 'о' },
    { text: 'прид..раться', letter: 'и' },
    { text: 'сж..гать', letter: 'и' },
    { text: 'прик..сновение', letter: 'о' },
    { text: 'м..кать (в краску)', letter: 'а' },
    { text: 'бл..стательный', letter: 'и' },
    { text: 'сч..тать', letter: 'и' },
    { text: 'зап..реть', letter: 'е' },
    { text: 'водор..сли', letter: 'о' },
    { text: 'подг..реть', letter: 'о' },
    { text: 'прил..жить', letter: 'о' },
    { text: 'отп..рать', letter: 'и' },
    { text: 'к..сание', letter: 'а' },
    { text: 'р..сток', letter: 'о' },
    { text: 'покл..ниться', letter: 'о' },
    { text: 'нат..реть', letter: 'е' },
    { text: 'р..стение', letter: 'а' },
    { text: 'прил..гательное', letter: 'а' },
    { text: 'ск..кать', letter: 'а' },
    { text: 'подл..жить', letter: 'о' },
    { text: 'ур..внение', letter: 'а' },
    { text: 'прот..реть', letter: 'е' },
    { text: 'сл..жение (чисел)', letter: 'о' },
    { text: 'выск..чка', letter: 'о' },
    { text: 'пл..вчиха', letter: 'о' },
    { text: 'пол..гать', letter: 'а' },
    { text: 'выр..щенный', letter: 'а' },
    { text: 'закл..нать', letter: 'и' },
    { text: 'Р..стов', letter: 'о' },
    { text: 'прим..рять (галстук)', letter: 'е' },
    { text: 'вн..мательный', letter: 'и' },
    { text: 'уб..ру', letter: 'е' },
    { text: 'подб..рёт (цвет)', letter: 'е' },
    { text: 'з..ря', letter: 'а' },
    { text: 'м..кать (в воду)', letter: 'а' },
    { text: 'заст..лить (постель)', letter: 'е' },
    { text: 'обм..кнуть (в краску)', letter: 'а' },
    { text: 'прил..жение', letter: 'о' },
    { text: 'пол..жение', letter: 'о' },
    { text: 'пл..вец', letter: 'о' },
    { text: 'вытв..рять', letter: 'о' },
    { text: 'оп..раясь', letter: 'и' },
    { text: 'раст..рать', letter: 'и' },
    { text: 'выр..внять (пол)', letter: 'о' },
    { text: 'см..чить (водой)', letter: 'о' },
    { text: 'р..стовщик', letter: 'о' },
]
// C Проверяемые корни
const typeC = [
    { text: 'благосл..вить', letter: 'о' },
    { text: 'благосл..вение', letter: 'о' },
    { text: 'ут..хать', letter: 'и' },
    { text: 'скр..вить', letter: 'и' },
    { text: 'скр..петь', letter: 'и' },
    { text: 'скр..петь(на морозе)', letter: 'и' },
    { text: 'ч..стоплотный', letter: 'и' },
    { text: 'ч..столюбивый', letter: 'е' },
    { text: 'ст..листический', letter: 'и' },
    { text: 'ув..дание(цветов)', letter: 'я' },
    { text: 'сист..матизация', letter: 'е' },
    { text: 'стр..мянный', letter: 'е' },
    { text: 'цв..ток', letter: 'е' },
    { text: 'вым..кнуть (под дождём)', letter: 'о' },
    { text: 'зап..роть', letter: 'о' },
    { text: 'вып..сть', letter: 'а' },
    { text: 'обн..жать', letter: 'а' },
    { text: 'отв..рить (овощи)', letter: 'а' },
    { text: 'г..ревать', letter: 'о' },
    { text: 'к..сички ', letter: 'о' },
    { text: 'просм..треть', letter: 'о' },
    { text: 'м..рячок', letter: 'о' },
    { text: 'д..ревья', letter: 'е' },
    { text: 'ум..ротворение', letter: 'и' },
    { text: 'в..дянистый', letter: 'о' },
    { text: 'л..нейка', letter: 'и' },
    { text: 'получ..совой', letter: 'а' },
    { text: 'в..здушный', letter: 'о' },
    { text: 'гр..мыхало', letter: 'о' },
    { text: 'тр..вяной', letter: 'а' },
    { text: 'зас..рять (природу)', letter: 'о' },
    { text: 'перекл..каться', letter: 'и' },
    { text: 'занав..с', letter: 'е' },
    { text: 'запл..сти', letter: 'е' },
    { text: 'дост..ваться', letter: 'а' },
    { text: 'задр..жала', letter: 'о' },
    { text: 'многог..лосье', letter: 'о' },
    { text: 'подсв..тить', letter: 'е' },
    { text: 'ст..кло', letter: 'е' },
    { text: 'передв..жение', letter: 'и' },
    { text: 'г..стевой (дом)', letter: 'о' },
    { text: 'г..лова', letter: 'о' },
    { text: 'об..щавший', letter: 'е' },
    { text: 'подм..гнуть ', letter: 'и' },
    { text: 'подв..ротня', letter: 'о' },
    { text: 'укл..ниться', letter: 'о' },
    { text: 'л..сток', letter: 'и' },
    { text: 'к..вать (головой)', letter: 'и' },
    { text: 'пл..чо', letter: 'е' },
    { text: 'зап..стись (провизией)', letter: 'а' },
    { text: 'непозв..лительно', letter: 'о' },
    { text: 'д..брота', letter: 'о' },
    { text: 'загл..денье', letter: 'я' },
    { text: 'насм..хаться', letter: 'е' },
    { text: 'скр..пучая', letter: 'и' },
    { text: 'пр..лестный', letter: 'е' },
    { text: 'св..сток ', letter: 'и' },
    { text: 'л..тательный (аппарат)', letter: 'е' },
    { text: 'разоч..рованный', letter: 'а' },
    { text: 'выч..сление', letter: 'и' },
    { text: 'к..лючий', letter: 'о' },
    { text: 'скр..пучий', letter: 'и' },
    { text: 'бл..готворительный', letter: 'а' },
    { text: 'к..фейный', letter: 'о' },
    { text: 'ог..рчаться', letter: 'о' },

]
// D Ы/И после приставок
const typeD = [

]
// E Ъ/Ь после приставок
const typeE = [
    { text: 'под..езд', letter: 'ъ' },
]
// F 
const typeF = [

]
// G Е/О после шипящих
const typeG = [
    { text: 'деш..вый', letter: 'е' },
    { text: 'к..фейный', letter: 'о' },
    { text: 'ог..рчаться', letter: 'о' },
]
// экспорт
export { typeA, typeB, typeC, typeD, typeE, typeF, typeG }